[phases.setup]
nixpkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'BUILD STARTED' && npm run frontend && echo 'BUILD COMPLETE'"]

[start]
cmd = "npm run backend"